### ISSUE TITLE
Closing the search bar doesn't work as intended

### ISSUE THREAD

**Issue by AayushMainali-Github** [USKhokhar/devoss#3]
Not sure if this is a bug or a 'feature', You need to do the same action twice to close the search bar. Also, it only happens on the main page. I tried it on the posts page it works as intended there.

**Laptop**
 - Windows 10
 - Chromium

https://github.com/USKhokhar/devoss/assets/94561475/0a71b52e-4352-48a2-a5c5-221f748f1d1a

**Comment by USKhokhar** [comment]
Thank you for reporting the bug. The problem (most probably) is that it is rendering two search modals when opened with <kbd>  ⌘ / CTRL + K  </kbd> on the home page _only_. Will look into it!

**Comment by AayushMainali-Github** [comment]
Goodluck!

**Comment by USKhokhar** [comment]
The bug is resolved. 
As expected, it was due to multiple rendering of the search modal. The previous code used the modal component twice on same page (app/page.tsx), one in the Header.tsx component and another in the Hero section (which was to be only shown in certain viewports). Due to this, two modals were triggered when pressed <kbd>  ⌘ / CTRL + K  </kbd>  on the Home page.

More on this in PR #4 

[View Live](https://devoss-git-master-uskhokhar.vercel.app/)

Thank you for contributing towards improving `devoss`.
